# fly.toml app configuration file generated for queue-terminal on 2023-07-31T23:03:27+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "queue-terminal"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
